"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

def tree(src):
    return [
        (root, map(lambda f: os.path.join(root, f), files))
        for (root, dirs, files) in os.walk(os.path.normpath(src))
    ]

APP = ['../src/APP.py']
#DATA_FILES = tree('../assets/') + tree('../webpack-demo/dist/') + ['../src/']
DATA_FILES = [
    ('assets', ['../assets/']),
    ('webpack-demo/dist/', ['../webpack-demo/dist/']),
    ('src', ['../src/']),
    'majsoul.icns',
    ]

OPTIONS = {
    'argv_emulation': False,
    'strip': True,
    'argv_emulation':True,
    'iconfile': 'majsoul.icns', # uncomment to include an icon
    'includes': ['WebKit', 'Foundation', 'webview', 'sys', 'os', 'json', 'time', 'csv'],
    'excludes': ['pyi_splash'],
    'plist': {
        'CFBundleName'   : 'majSoulRP',     # 应用名
        'CFBundleDisplayName': 'majSoulRP', # 应用显示名
        'CFBundleVersion': '1.0.0',      # 应用版本号
        'CFBundleShortVersionString':'0.1.0',
        'CFBundleIdentifier' : 'majSoulRP', # 应用包名、唯一标识
        'NSHumanReadableCopyright': 'Copyright © 2021 SW Zirpon.Zhang. All rights reserved.', # 可读版权
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)